apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: inventory-deployment 
  labels: 
    app: inventory 
spec: 
  selector: 
    matchLabels: 
      app: inventory 
  template: 
    metadata: 
      labels: 
        app: inventory 
    spec: 
      containers: 
      - name: inventory-container 
        image: quay.ocp4.demo.com/user1/inventory:1.0-SNAPSHOT 
        ports: 
        - containerPort: 9080 
--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: inventory-service 
spec: 
  type: ClusterIP
  selector: 
    app: inventory 
  ports: 
  - protocol: TCP 
    port: 9080 
    targetPort: 9080 
